version: "3.9"

services:
  demo-app:
    image: eclipse-temurin:17.0.7_7-jdk-jammy
    network_mode: host
    volumes: [ ./:/app ]
    working_dir: /app
    tty: true
    environment:
      - WLP_DEBUG_REMOTE=y
